# Change these first
owner: timbru31 # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Dustplanet
    url: https://dustplanet.de
  - name: Jenkins
    url: https://ci.dustplanet.de
  - name: Artifactory
    url: https://repo.dustplanet.de
  - name: Roundcube
    url: https://mail.dustplanet.de
  - name: Nextcloud
    url: https://nextcloud.dustplanet.de

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.dustplanet.de
  # Uncomment the following line if you don't have a custom domain and add your repo name
  #baseUrl: /upptime
  logoUrl: https://dustplanet.de/wp-content/uploads/2014/08/favicon_neu.png
  name: Dustplanet's upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub to monitor services at Dustplanet."
  introMessage: This status page shows **real-time** data from our [GitHub repository](https://github.com/dustplanet/upptime). In case of an incident please either report it on [Discord](https://discord.gg/EZbr6Ks) or via [e-mail](mailto://admin@dustplanet.de)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/dustplanet/$REPO
    - title: Jenkins
      href: https://ci.dustplanet.de
    - title: Artifactory
      href: https://repo.dustplanet.de

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
